[package]
name = "rustorr-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
bytes.workspace = true
rustorr-domain.workspace = true
rustorr-cache.workspace = true
anyhow.workspace = true
librqbit.workspace = true
librqbit-core.workspace = true
percent-encoding.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["fs", "io-util", "sync", "time"] }

[dev-dependencies]
tempfile.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "io-util", "time"] }

[lints]
workspace = true
