FROM debian:bookworm-slim

RUN apt-get update \
    && apt-get install --no-install-recommends -y opentracker \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 6969
ENTRYPOINT ["/usr/bin/opentracker"]
CMD ["-p", "6969", "-P", "6969", "-d", "/data", "-w", "whitelist.txt"]
